language: java
install: mvn install -DskipTests=true -Dgpg.skip=true -Djavadoc.skip=true
script: mvn package -DskipTests=true -Dgpg.skip=true -Djavadoc.skip=true
before_deploy:
- export RELEASE_JARS=$(ls target/*.tar.gz)
- echo "deploying RELEASE_JARS to GitHub releases"
deploy:
  provider: releases
  file_glob: true
  file: target/*.tar.gz
  skip_cleanup: true
  api_key:
    secure: V39OsdYFu6W5sqvqUljnfSOm+qm+27UcC/bvAr0IwrVGTJezprDwlHXpScT3pvoJzEPRap9uaz1XAe/6rqbzAvvh6UmAZXb4/aHn2RYhaPpCSiChm6aY49VOwK2nUe4A4Ww38/YcReiXN18+B0MdByXVT4ADsamNRI9LEbuX5liW7PqCRsvFiKge7W/yQ4MUT0rI8TA80tx0EzLDmKEs3YrbUMOu6T0c9Dl80yIHcutZjXBZe7G0dFvtdr+8R+AbCoMqd8IPOZwi1V55OxHdXmokHm5RwnCTtkecm3iJ9oWqASr03EiQc9mbYPwahvQEsyWUwH9jr8R9Wc+/B2mULZSZnt+Un4DlAS0WjwkdKehK8a2bGdmqddqJF8TY/fJl5HNlbuC0Qcx38pjL8JHgoGNINZaVoIKbRYhMnfCfDqNKRpL8VOIts0Pc567Ow7kD+qPj6zUHZ3m2TQZ4iIk+mhl7c1AhwabFLeF+tEtmlDvX0YP/NtIonOls61Y6su2TYh6xrhLvgdR594zM3dKojsPXLjocSSPj9Jkc3GOCYBRlQq97BCKnU5nN9x0d9Wc/jLzhwqsIGFxeEYBrxmZBbidV6R98FCswPrWg7RBkvGARgZEMGdxMOOWeVvuLHGziHWJt5zGWYjk2BrNfsCYB3irr5yr5/H9nJ27N+BnV2jw=
  on:
    tags: true
